### ISSUE TITLE
/wildtp

### ISSUE THREAD

**Issue by Zike777** [Qballl/WildernessTp#10]
When i try to make the console execute wild on a player i get the following error. Im sure this is probably something on  my end but, any ideas how to fix it? Here is a link to the to the console error. Thank you.

http://pastebin.com/W6A3zeYH

**Comment by Qballl** [comment]
Seems I made an error on my end I will go work on this thank you for reporting this and Im sorry I didn't get to you in the irc.

**Comment by Zike777** [comment]
Its all good man. Its nice to know this is new issue that we can fix. Looking forward to getting this to work. Thank you.

**Comment by Qballl** [comment]
Can you confirm this only happens with console?

**Comment by Zike777** [comment]
Ill go test now

**Comment by Zike777** [comment]
It seems like its only with the console, everything else appears to be working at this time

**Comment by Qballl** [comment]
Well then my theory is back to being anything

**Comment by Qballl** [comment]
Alright my theory was right and I know what the problem is. The player is in a world in which the command is not allowed.

**Comment by Zike777** [comment]
interesting, ill have to research farther on my end. Thank you very much

**Comment by Qballl** [comment]
If you want I will help you setup your config

**Comment by Zike777** [comment]
Can you help me set up a portal that will rtp players?

Also using fbasics but have disabled the wild feature that is built into that, so hoping it don't conflict.

**Comment by Qballl** [comment]
Yes I can

**Comment by Zike777** [comment]
188.165.254.75 im on now, /server factions once you join hub

**Comment by Qballl** [comment]
You will have to give me some time to open minecraft

**Comment by Zike777** [comment]
no problem its 1.8.8

**Comment by Qballl** [comment]
Yea I got that from the error
