### ISSUE TITLE
[BUG] Duplicate chat messages when waiting to teleport

### ISSUE THREAD

**Issue by aco4** [Qballl/WildernessTp#100]
**Describe the bug**
Sometimes when waiting to teleport, the chat messages that countdown are duplicated.

**To Reproduce**
1. /wild
2. See error

**Expected behavior**
No duplicate messages should appear.

**Screenshots**
https://cdn.discordapp.com/attachments/601549201867800587/884329678100385882/unknown.png
https://cdn.discordapp.com/attachments/612002578489671710/886026349754581048/unknown.png

**Additional context**
I think it happens when multiple players use the teleport at once.

**Comment by BalinGrant** [comment]
Closing as this is likely fixed with a newer version which has been released in the meantime.
