### ISSUE TITLE
[BUG] (Apparent) Memory Leak on 1.20.1

### ISSUE THREAD

**Issue by Hipposgrumm** [Qballl/WildernessTp#104]
I don’t know if this has anything to do with my server host (Exaroton), my server software (Paper), or maybe I screwed up my configs somehow, but whenever I run this plugin on 1.20.1 (not yet stated as tested on SpigotMC), the game runs normally at first, then tick rate starts to decrease before the server just can’t handle it anymore and crashes. This all happens within the span of 5-10 minutes (with 2GB of RAM), and with my knowledge of computers I can determine that this is a memory leak.

I would love to supply a log of the crash, but Exaroton is stupid and deletes old logs, so I will have to reinstall the plugin and wait for it to crash again. I will update this issue when I can get a new log.

**Comment by RonaldBunk** [comment]
Hi,

Could you post the results of /timings (After it ran for a couple of minutes/hours)?

**Comment by Hipposgrumm** [comment]
I just realized that I have left this hanging for quite a while now.
I am no longer in the position to be able to attempt to reproduce the issue, so we can probably just close it.
