### ISSUE TITLE
Make Portal and Vaults support Optional

### ISSUE THREAD

**Issue by DreamConspiracy** [Qballl/WildernessTp#11]
Could you add a config option for whether one wants to use the Portals and Economy functionality? Or even better, just automatically test if those plug-ins are installed. And if not then could you please properly list those plug-ins as dependencies so that I don't get an error every time I start up my server? Thanks.

**Comment by Qballl** [comment]
Economy can be disabled by setting cost to zero and portals doesn't require any dependencies

**Comment by Qballl** [comment]
My bad the economy is needed I will fix this in a new update

**Comment by Qballl** [comment]
Download the latest dev build from the target folder on the git repo main page
