### ISSUE TITLE
Version 3.8.3

### ISSUE THREAD

**Issue by idnthvn** [Qballl/WildernessTp#12]
Using Thermos 1.7.10 version 57
When using /wild
spawns me at level 262, gives me protection and has me fall/drop down to the ground.
Is this normal?
Nether is finally working now properly since last time where i am not above the bedrock and not below the bedrock and actually in between 1- 127. However, i am spawning just inside the block, like half way in?
i can jump out and move, but than spawns me back in there. the only way i can get out is to break the blocks directly below me. 

Again i am using Thermos 1.7.10 forge 1614 version 57. (58 is neweer but has issues)

If you need to test anything let me know. 
My modpack is TechnicalTrials.
http://www.technicpack.net/modpack/litebox.741396

Let me know if thre is anythign i can help with

**Comment by Qballl** [comment]
Well that is not normal but for me on my spigot test server I have not had it spawn me in the air that high in long time. I will see what I can do to fix it
