### ISSUE TITLE
Plugin wont work

### ISSUE THREAD

**Issue by AceAI2** [Qballl/WildernessTp#13]
So , The plugin is marked as red (Wild)
And before it was marked red , everything didnt work aswell , 
Now the thing is, ive checked if there are any errors in the config ,but nothing.
Could u please help set up this plugin?
Config.yml for Wild : https://hastebin.com/avikafafes.bash
Portals.yml for Wild : Portals: {}
Config.yml for WildTP : https://hastebin.com/alubodotuk.coffeescript
Storage.yml for WildTP : Cooldowns: {}

**Comment by Qballl** [comment]
Can you send your full startup log

**Comment by Qballl** [comment]
Also seems you have two wildtp plugins

**Comment by AceAI2** [comment]
Yeah , Had two plugins for some reason , Thanks , it works now!

**Comment by Qballl** [comment]
Glad to hear
