### ISSUE TITLE
No suitable locations found error always occurs

### ISSUE THREAD

**Issue by cupOfJava2014** [Qballl/WildernessTp#14]
I am playing on my own Spigot 1.12 server and even with 1000 retry opportunities it still says "no suitable locations found" every time.

**Comment by cupOfJava2014** [comment]
It does not appear the plugin likes to teleport players farther from 50km from the origin. Hm.

**Comment by cupOfJava2014** [comment]
Ah never mind. It appears my map creator did not make the world larger than 4096x4096.

**Comment by Qballl** [comment]
Good to see you figured out the problem
