### ISSUE TITLE
Portal Permissions

### ISSUE THREAD

**Issue by xcamnhamx** [Qballl/WildernessTp#15]
Do you have any permissions for the portal? I tried adding wild.wildtp but doesn't work. Thanks for making this plugin so awesome.

**Comment by Qballl** [comment]
There is no perm to use it as all users can use them without needing the perm are you sure you made the portal right or that it's not a biome portal?

**Comment by Qballl** [comment]
Hey have you fixed your problem yet?

**Comment by Qballl** [comment]
@xcamnhamx Are you still having issues?

**Comment by Qballl** [comment]
Im going to go ahead and close this issue as you have not responded. Please not you can still commet on the closed on and I will be notified.
