### ISSUE TITLE
Wild Rework

### ISSUE THREAD

**Issue by Idan330I** [Qballl/WildernessTp#16]
I would suggest a wild rework like this:
1- /wild would bring up a gui that you can select what world you would go to making a multiverse support mabe selecting what worlds in the config
2- When you select the world it could bring up another gui to select how distant from the spawn it would tp and make cost for it so players wont spam it at exaple: 1000-2500 block from spawn cost in the config and the distance in the config
3- No tp in a base or near like 5 chunk or set in the config from it
Hope to see it in the plugin! =D

**Comment by Idan330I** [comment]
Yay one thing you should colaborate with @MarkehMe!

**Comment by Qballl** [comment]
Im still considering doing this but it requires a major rework of everything and I see no benefit  at this time

**Comment by Idan330I** [comment]
Oh ok
