### ISSUE TITLE
Not properly exiting out of /wildtp GUI turns off chat function

### ISSUE THREAD

**Issue by SiuanSong** [Qballl/WildernessTp#17]
Not hitting the redstone block breaks chat.  I was able to send commands but not chat.  There were no warnings at all.  Thankfully, that was the only plugin I was working with at the time so it was relatively quick to figure out.

**Comment by Qballl** [comment]
I will add a failsafe but the redstone block is the way tp get out

**Comment by Qballl** [comment]
Update cannot add fail-safe dude to how guis work at this time.

**Comment by SiuanSong** [comment]
Any way to add a message that says something along the lines of "Please exit out of /wtp GUI before chatting."

**Comment by Qballl** [comment]
I can try but it would be hard as each inventory change closes it. I'll think of something

**Comment by Qballl** [comment]
Im gonna try to figure out a way to send a message either on close or on the open I will probably do on open

**Comment by SiuanSong** [comment]
That would be awesome! THank you

**Comment by Qballl** [comment]
Added on local build

**Comment by SiuanSong** [comment]
Local build?  I just did this again and couldn't remember how to fix it or what caused it for about 30 minutes.
using version 3.14.15 on spigot 1.13.2

**Comment by Qballl** [comment]
Hmm at this point it should be in the production one
