### ISSUE TITLE
Invalid plugin.yml?

### ISSUE THREAD

**Issue by RainOfPain125** [Qballl/WildernessTp#18]
https://pastebin.com/WBKTHnzD

My server couldn't load it's own spigot.yml and paper.yml, but after deleting those and having new ones generate it also said the wild plugin has an invalid yml. I haven't touched it in a while...

I'm using Paper Spigot. git-Paper-1390

**Comment by Qballl** [comment]
Try redownloading wild as I downloaded a version yesterday to test and it worked fine.

**Comment by Qballl** [comment]
Any updates?
