### ISSUE TITLE
Plugin displaying cooldown incorrectly. 

### ISSUE THREAD

**Issue by Castiella** [Qballl/WildernessTp#20]
Just to clarify, the cooldown does work. You set it to 120, and it will allow the player to teleport again in 120 secs. However, it is an issue with the DISPLAY of the cooldown message i am reporting - it is very confusing for players.

How to replicate issue:

Set cooldown to 120.
config is as follows: Cooldownmsg: '&4You must wait {rem} seconds until you can travel again!'

In game you see (as displayed in screenshot):
"You must wait 022 minutes, 22 seconds until you can travel again"

if you continue to spam the /wild command it does this:
https://imgur.com/a/4hOg29W

Issue:
Plugin seems to display that there are 023 mins left, ALONGSIDE the 023 seconds. when in actual fact there are 23 seconds left, not minutes.

How to resolve: remove the "you must wait 023 minutes," from the plugin, so it just displays the correct seconds.

**Comment by Qballl** [comment]
Thanks for reporting this I will look into this

**Comment by Qballl** [comment]
Turns out it was already fixed on my end Update posted on spigot
