### ISSUE TITLE
If you do /wild and then move to cancel it and then do /wild again you'll be teleported twice

### ISSUE THREAD

**Issue by mart-r** [Qballl/WildernessTp#22]
When you do /wild and then move to cancel that action and then do /wild a second time and wait for it to work, you'll first be teleported to one spot and then to another spot.

How to reproduce:
`(need to have a wait time)
/wild
move to cancel the command
/wild
wait while you get tp
ed`

**Comment by Qballl** [comment]
I've known about this for a while. I just haven't had time to try to fix it yet I will try to fix it soon.
