### ISSUE TITLE
I get an error when using a sign

### ISSUE THREAD

**Issue by JoshHeng** [Qballl/WildernessTp#24]
17.07 17:38:29 [Server] INFO JTwhizzkid placed a sign @ SurvivalAlpha: x251, z267;====================;[Wild];====================
17.07 17:38:31 [Server] ERROR Biome wild sign at SurvivalAlpha,252,75,266 has a biome or a world that is incorrect please fix
17.07 17:38:31 [Server] ERROR Biome wild sign at SurvivalAlpha,252,75,266 has a biome or a world that is incorrect please fix
17.07 17:38:31 [Server] ERROR Biome wild sign at SurvivalAlpha,251,75,267 has a biome or a world that is incorrect please fix
17.07 17:38:32 [Server] ERROR Biome wild sign at SurvivalAlpha,251,75,267 has a biome or a world that is incorrect please fix

What do I change in the config?

**Comment by Qballl** [comment]
Can you show me what you are putting on the sign?

**Comment by JoshHeng** [comment]
1st Line: WildTp | 2nd line: [Wild] | Nothing on 3rd or 4th line. The sign does reformat to the coloured [Wild] sign and it says it has been created

**Comment by Qballl** [comment]
Probably me doing something simple stupid like not cancelling out if the lines are blank

**Comment by Qballl** [comment]
Is there anything on the last line of the sign?

**Comment by JoshHeng** [comment]
No

Thanks,
Joshua Heng

**Comment by Qballl** [comment]
Weird I can't seem to get this to happen+

**Comment by Qballl** [comment]
hmm this is weird I finally was able to test it for myself and well it causes the error

**Comment by Qballl** [comment]
Well I figured it out made a noob mistake of checking if the line is null which it never is
