### ISSUE TITLE
Bug damage

### ISSUE THREAD

**Issue by Rosu-Catalin** [Qballl/WildernessTp#25]
https://gyazo.com/a9a7b3c53828a965fd81098c496b8fb7

**Comment by Qballl** [comment]
What server version?

**Comment by Rosu-Catalin** [comment]
1.12.2

**Comment by Qballl** [comment]
Quick question can you send your config and what plugin version are you using?

**Comment by Rosu-Catalin** [comment]
3.14.5 VER and config default.

**Comment by Qballl** [comment]
Can you confirm whether or not this is happening in the latest version on spigot?

**Comment by CircusCow** [comment]
This is currently happening to me.

**Comment by Rvby1** [comment]
Hey, I'm having this issue on a 1.14.3 Paper server using the latest Wilderness-Tp from the Spigot website. Happens to all players, even Ops. Players are in open air, but don't stop taking suffocation damage until they die. Players can move around without a problem, and the terrain around them loads. 
You can find my config here: https://pastebin.com/3LMdb1ug
