### ISSUE TITLE
/wild takes everyone to the same spot, every time.

### ISSUE THREAD

**Issue by Castiella** [Qballl/WildernessTp#26]
Hi there!

When someone does /wild they go to the same area, every time. 

Here is my latest log for info.

[latest.log](https://github.com/Qballl/WildernessTp/files/2370761/latest.log)

**Comment by Qballl** [comment]
Send your config

**Comment by Castiella** [comment]
[config.yml.txt](https://github.com/Qballl/WildernessTp/files/2371394/config.yml.txt)

**Comment by Qballl** [comment]
I see the problem you smponepointthirteen world is `smponepointthirteen: {}` and not smponepointthirteen :
    MinX: num
    MaxX: num
    MinZ: num
    MaxZ: num
How did you add the world to the config?

**Comment by Qballl** [comment]
Have you fixed your issue yet?

**Comment by Qballl** [comment]
Assuming fixed gonna close this if not just post a comment and I'll reopen
