### ISSUE TITLE
No locations found

### ISSUE THREAD

**Issue by QueenKisaki** [Qballl/WildernessTp#29]
whoops hit enter too soon...
so no matter command (.wild or /wildtp etc) it will do the countdown but cannot find a location. I dont have a map maker like I saw another post explain so I'm not sure why it is not working

Worlds:
  world:
    MinX: 0
    MaxX: 50000
    MinZ: 0
    MaxZ: 50000
  Megara:
    MinX: 0
    MaxX: 50000
    MinZ: 0
    MaxZ: 50000

is in my config and I'm using a 1.13.1 server with your most recent version, if that helps. No errors in console or anything either

I changed this to false
InvertYSearch: false
and it worked.

**Comment by Qballl** [comment]
Weird. Config looks right so I'll have to look at the code soon

**Comment by QueenKisaki** [comment]
Yea like I said, after changing InvertYsearch to false the /wild command worked but still having the countdown with no suitable locations for the biome commands.

**Comment by Qballl** [comment]
Just an fyi inverty searches from bedrock up so you may find caves if thats what you want.  Thanks for telling me about biome
