### ISSUE TITLE
i have lagg in 1.13.2

### ISSUE THREAD

**Issue by successed** [Qballl/WildernessTp#32]
please fix this : http://prntscr.com/mjeobr

**Comment by Qballl** [comment]
Known issue I am working on this but I am very busy.  For now, a fix is to use this version https://www.spigotmc.org/resources/wilderness-tp.18431/download?version=252854. If you use FAWE or Kingdoms though the hooks won't work

**Comment by Qballl** [comment]
Believed to have this fixed
