### ISSUE TITLE
Make wild command run async

### ISSUE THREAD

**Issue by FixTheAdmin** [Qballl/WildernessTp#33]
Hello, I run https://earthmc.net and I really enjoy your plugin. Unfortunately the server freezes for everyone while the plugin is trying to find a wild-location. It would be very much appreciated if you could make this process async.

**Comment by Qballl** [comment]
Kinda of a known issue I am looking into potential fixes

**Comment by FixTheAdmin** [comment]
I will paypal anyone 15$ able to patch this issue.

**Comment by Qballl** [comment]
Im working on something currently it has reduced the lag to about 1 sec to almost instant in most cases if you would care to test just tell me. Also there is the problem that the bukkit api cannot be accessed async

**Comment by Qballl** [comment]
@FixTheAdmin Would you mind testing the new version I'm working on https://github.com/Qballl/WildernessTp/raw/TempFix/target/WildTp.jar I need a larger sample size other than me with my local server that is running my client and like 30 chrome tabs

**Comment by FixTheAdmin** [comment]
The build works much better! It does not seem to check bioms though

**Comment by Qballl** [comment]
That is great to know. Are you getting any lag at all? Also, the biome thing is probably me forgetting a line of code I recoded a decent amount of the location search for this.

**Comment by FixTheAdmin** [comment]
The lag is not noticeable with over 100 players online, well done. When the biome check gets back there is nothing to complain about.

**Comment by Qballl** [comment]
That is great to hear. Please tell me all the problems so far. Also by biome check you mean like /wild Plains and then going to plains only?

**Comment by FixTheAdmin** [comment]
Sorry for being unclear. I have several blacklisted biomes in the config file but players still spawn in blacklisted biomes.

**Comment by Qballl** [comment]
Thanks for clarifying I shall look into it

**Comment by Qballl** [comment]
Redownload from the link above it should include the blacklist biome.

**Comment by FixTheAdmin** [comment]
Players are still spawning in blacklisted bioms

**Comment by Qballl** [comment]
Alright I will have to look into this
