### ISSUE TITLE
/wild only teleports you on the positive X and Y

### ISSUE THREAD

**Issue by Davidozs** [Qballl/WildernessTp#35]
Hi,

I have setup the /wild plugin and everything works. I have set the minimum X and Z for 4000 and the max at 8000. I dont want people to spawn under 4000 on X and Z or above -4000 on X and Z. How do I setup the /wildtp set command so that people can spawn lower than -4000 on X and Z, and above 4000 on X and Z?

**Comment by Qballl** [comment]
Pastebin in your config. Also, the plugin doesn't assume that the min is negative you have to put the - in there. I cannot assume it is negative as there may be some rare cases where it will be positive.

**Comment by Davidozs** [comment]
https://pastebin.com/gC1wr70v

**Comment by Qballl** [comment]
Based on what you told me you want to set your min on smartsurvival to -4000 and your max to 4000 as I said before the - is needed

**Comment by Davidozs** [comment]
But if I do that, it will not teleport me above -4000 and 4000. Let me draw this out:
![image](https://user-images.githubusercontent.com/52178206/60191493-b2620380-9834-11e9-91d3-d59c3bc7f452.png)

green is the area I want people to random teleport in with /wild, red is the place where I dont want them. In text: I want people to teleport under 8000 and above 4000 on both X and Z, and I want them to teleport above -8000 and under -4000 on both X and Z. I'm sorry if it still isn't clear.

**Comment by Qballl** [comment]
You can't just exclude a part in the center. Why are you trying to do that anyway?

**Comment by Davidozs** [comment]
I don't want people to do /wild then go like 100 blocks from spawn.

**Comment by Qballl** [comment]
Trust me when I say the chances of that are low like next to none

**Comment by Davidozs** [comment]
Alright, I'll just live with it. No problem. Thanks for the help anyway.

**Comment by RonaldBunk** [comment]
Actually, I can propose two solutions:
**1:** Set minX, minZ to a minimum of your spawn coordinates (This will most likely result in only positive-coordinate teleportation as aside effect.
**2:** I can implement a hook into WorldGuard (If it doesn't exists yet) and you have to use WorldGuard to protect your spawn area.
