### ISSUE TITLE
Is it posible to only use signs to /wild and not the command?

### ISSUE THREAD

**Issue by Davidozs** [Qballl/WildernessTp#36]
Exactly as the title says, I want players to only be able to use the sign at spawn to teleport into the wild, not by using /wild.

**Comment by Qballl** [comment]
It appears I unintentionally removed that ability I'll make sure to work it back in

**Comment by Davidozs** [comment]
Thanks alot, no need to rush.

**Comment by Davidozs** [comment]
No need to rush, but is there an ETA? :)

**Comment by Qballl** [comment]
Not yet I will try to get it in, in under a week

**Comment by Davidozs** [comment]
Thanks :)

**Comment by Qballl** [comment]
Hey I told you wrong as I looked at the code on github at work. Although looking at the perms checking made me find a few issues and fixed those. The latest version of the plugin does not require players to have the wild.wildtp perm to use signs/portals.

**Comment by Davidozs** [comment]
Sorry, I don't quite understand, can I remove the wild.wildtp permission from players now, and they will still be able to use the signs?

**Comment by Qballl** [comment]
Yes they should be able to

**Comment by Davidozs** [comment]
Alright, I can’t test it right now, but l’II let you know if it does or doesn’t work.

**Comment by Davidozs** [comment]
It doesn't work for me, I have removed the wild.wildtp permission and the wild.wildtp.world.smartsurvival, and I can't use both /wild and the sign. I have also tried to only have the wild.wildtp.world.smartsurvival permission only but then I can access both /wild and the sign. How would I make players only able to use the sign, not /rtp or /wild?
