### ISSUE TITLE
Teleport to a random location when player respawn

### ISSUE THREAD

**Issue by jyhsu2000** [Qballl/WildernessTp#39]
Hi, I have an idea but I'm not sure about the feasibility.
After a player dies, is it possible to teleport the player to a random location if he didn't sleep on a bed or the bed is missing?
(Maybe with an option in config to toggle it)

That means if a player dies,
- If he has slept on a bed and the bed still exists, respawn at bed's location. (Normal behavior in Minecraft)
- If he has no bed, respawn at a random location. (Handling by this plugin)

I've check the docs and found there is a [PlayerRespawnEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerRespawnEvent.html) contains `isBedSpawn​()` and `setRespawnLocation​(Location respawnLocation)`.
Maybe it's a way to implement it?

**Comment by Qballl** [comment]
Yea shouldn't be too hard

**Comment by Qballl** [comment]
Implemented in 4.x now too
