### ISSUE TITLE
Sounds still messing up

### ISSUE THREAD

**Issue by Aritex1** [Qballl/WildernessTp#4]
I have downloaded the new version which still comes out as v2.0 in the console even though its v2.1, even tried this on a fresh server and its still coming back v2.0

Either way its still saying the sounds are messed up, perhaps you uploaded the wrong file?

**Comment by Qballl** [comment]
No I know that is the right file but I never changed the version in plugin.yml as I was in a rush to fix this right when I found it. Could you provide a log or some more details. And which sounds are you using as I just recently was on my test server (1.8.8) and found out the ghast sounds don't work. And this is on my list of to look into tomorrow or when I finish this paper I have to right for school. So please make a pastebin of the log or give more details ie what sounds were you using

**Comment by Aritex1** [comment]
It doesnt provide any detail, it just says the sound cannot be found then disables the plugin
I am using the default config.yml. Does it have any prerequisites?

**Comment by Aritex1** [comment]
[19:19:13] [Server thread/INFO]: [Wild] Enabling Wild v2.0
[19:19:13] [Server thread/INFO]: Error specifed sound cannot be found please check config
[19:19:13] [Server thread/INFO]: Disabling plugin
[19:19:13] [Server thread/INFO]: [Wild] Disabling Wild v2.0

**Comment by Qballl** [comment]
Update I just realized my mistake you see I copied my sound class for another plugin and named it the same so only it was changed Ill send you a fixed version for sure here in 3 minutes as its as simple as changing a few things.

**Comment by Aritex1** [comment]
:) Thanks

**Comment by Qballl** [comment]
Here you go so sorry for that had to zip it wont let me send as jar thanks for reporting this. Please tell me if it works
[WildTp.jar.zip](https://github.com/Qballl/WildernessTp/files/168321/WildTp.jar.zip)

**Comment by Aritex1** [comment]
Didnt work :( same error

**Comment by Aritex1** [comment]
Running latest 1.9 spigot.

**Comment by Qballl** [comment]
hmm
I know its compatible with 1.9 let mee look closer at the got

**Comment by Qballl** [comment]
I see I sent the wrong one

**Comment by Qballl** [comment]
Now send what i know is the correct one b/c I deleted all exsiting ones 
[WildTp.jar.zip](https://github.com/Qballl/WildernessTp/files/168334/WildTp.jar.zip)

**Comment by Qballl** [comment]
Please tell me of any errors

**Comment by Aritex1** [comment]
Thank you for your help Qballl, :) :+1: Have a great rest of your day.

**Comment by Qballl** [comment]
Did that version work?

**Comment by Qballl** [comment]
I will assume yes but just want to be sure and same to you about the day

**Comment by Aritex1** [comment]
Yes it did.

**Comment by Qballl** [comment]
Glad to hear it now time to go post on spigot

**Comment by Qballl** [comment]
Thank you so much for reporting this and sticking with me it can be a bumpy road sometimes as a dev

**Comment by Qballl** [comment]
Kinda surprised no one else reported this besides you. Thank you for that god this makes me look so bad in the world of plugin devs :P
