### ISSUE TITLE
error when executing /wild

### ISSUE THREAD

**Issue by stw222** [Qballl/WildernessTp#42]
when a player executes /wild, they seem to have like a 1 in 5 chance for it to actually teleport them. when it doesnt work, it still takes their money.

Paper-97 for mc 1.14.2
error:
[https://pastebin.com/rgeJtkLn](https://pastebin.com/rgeJtkLn)

Config:
[https://pastebin.com/SyAwryYK](https://pastebin.com/SyAwryYK)

plugins:

- actionbar api
- announcer
- arnorstand tools
- async world edit
- better sleep
- buycraftx
- chunk spawner limiter
- citizens
- core protect
- crazy auctions
- discordSRV
- dynmap
- editable signs
- essentialsx
- greifprevention
- head database
- heads plus
- holographic displays
- HorseTPWithMe
- marriage master
- matrix
- mcmmo classic
- mineable spawners
- mob capture
- mobhunting
- multiverse core
- multiverse inventories
- multiverse netherportals
- multiverse portals
- multiverse signportals
- nerf phantoms
- openinv
- permissionsex
- placeholder api
- plot2dynmap
- plotsquared
- protocol lib
- server list plus
- tab
- tempfly
- vault
- voting plugin
- wildernesstb
- world edit
- world guard

**Comment by AIGLEZMA** [comment]
i don't think there is a biome named "Hell"
