### ISSUE TITLE
Worlds that have periods in the name don't work

### ISSUE THREAD

**Issue by m1stadev** [Qballl/WildernessTp#43]
Trying to set this plugin up on my server, but my server world is named spigot-1.14.2-dev, and when it's added in the config and I send it to the server, it doesn't apply for some reason. If I add it in game, then the config will say this. I would rename the server world, but then I'm pretty sure I would need to change all of my plugin configs to say that
```  spigot-1:
       '14':
         2-dev:
           MinX: -50000
           MaxX: 50000
           MinZ: -50000
           MaxZ: 50000

**Comment by Qballl** [comment]
Nothing I can really do would have to change how worlds are stored. YML reads periods as a new path

**Comment by RonaldBunk** [comment]
@M1staAwesome I can fix it, but it would require you to quote the name like 'my.dummy.world'. However I would recommend to not use periods and stick with the regular punctuation.
