### ISSUE TITLE
Wilderness teleport causes extreme lag on 1.14.4 Paper, build 152.

### ISSUE THREAD

**Issue by Weasel-Beans** [Qballl/WildernessTp#46]
https://timings.aikar.co/?id=dea08f32ef234182a8843880bac01445

My server has been getting huge amounts of lag regularly which seems to come at least in great part due to /wild usage I believe. All the chunks in that area are pre-generated.

All teleportation seems to cause big lag, I think it's mainly an issue with 1.14

**Comment by AIGLEZMA** [comment]
i also think it's an 1.14 issue cause i added a async teleport (paper only) so i'm gonna try to fix it or make it configurable :)
