### ISSUE TITLE
Change name of plugin

### ISSUE THREAD

**Issue by hornta** [Qballl/WildernessTp#49]
Hi.
I own a plugin called "Wild" on SpigotMC and I want to use the bstats Metrics but I am unable to do so since there is already a plugin called Wild in there. 
Would it be possible to change the name of this plugin in the plugin.yml to WildernessTP or something other than Wild? 

EDIT:
I see that there are a PR with the name change https://github.com/Qballl/WildernessTp/pull/48/files
So will you also change the name in the bStats page?

**Comment by Qballl** [comment]
For name the name is not changing maybe once the full rewrite is done but that is gonna take some time

**Comment by RonaldBunk** [comment]
Actually, as I implement Release 4.0.0 of this plugin, I did in fact name it WildernessTP as it's formal name.
