### ISSUE TITLE
Cooldown Message Not Showing

### ISSUE THREAD

**Issue by wumbly12** [Qballl/WildernessTp#55]
Hey man,

The plugin is working perfectly for me, other than the fact that the teleport cool down message does not display in chat. I've gone through the config multiple times but cannot get this message to display. 

My config for the cooldown message is the default message.

When the cooldown is activated and I try to type /wild , it looks like a message is sent in chat but it has no text.

Example here: https://i.imgur.com/ZLFWBCU.png

The empty text bar below "Thrown to a random location..." is what displays when the cooldown message should display.

 Any help would be appreciated.

Thanks.

**Comment by Qballl** [comment]
If I recall I fixed this locally I think it was I had changed the way something was spelt
