### ISSUE TITLE
Unable to remove sound and potion effects!

### ISSUE THREAD

**Issue by pjt0720** [Qballl/WildernessTp#61]
Hello I am currently having an issue removing the sound and potion effects. I dont want my players to have potion effects when they teleport and I just dont really care for sounds when using the command. I have tried to leave the area blank in the config, but the plugin seems to put them back when restarting the server. Is there a way to make it so there is no noise when teleporting and is there a way to disable the potion effects?

Thanks
pjt0720

**Comment by Qballl** [comment]
Are you sure you are saving the config. The sound I dont think I made a way to disable, however for the potions you will just want to have an empty bracket ie potions: []
