### ISSUE TITLE
Resource info failed

### ISSUE THREAD

**Issue by srnyx** [Qballl/WildernessTp#62]
I get this error when loading WildTP:
`16.11 09:04:04 [Server] WARN [Wild] Failed to get resource info from spiget.org`

**Comment by Qballl** [comment]
Odd your host must not allow internet access or that site went down for a bit. Any thats just for the auto update

**Comment by srnyx** [comment]
Yeah just reran right now, still the same error, I'm just going through my console today reporting all errors I find for all plugins.

**Comment by Qballl** [comment]
Odd I will have to see whats up
