### ISSUE TITLE
CANT USE /WILD IN THIS WORLD

### ISSUE THREAD

**Issue by xxyaboimazinxx** [Qballl/WildernessTp#63]
when i do /wild i get CANT USE /WILD IN THIS WORLD

**Comment by Qballl** [comment]
Have you configured the plugin have you given permissions?

**Comment by xxyaboimazinxx** [comment]
> Have you configured the plugin have you given permissions?

Well it said it automatically gave the user the permission. That’s what I want help with, the config.

**Comment by Qballl** [comment]
Pastebin ypur config and tell me the world name

**Comment by xxyaboimazinxx** [comment]
sure world name is factions https://pastebin.com/raw/L3kfGsfJ

**Comment by Qballl** [comment]
https://pastebin.com/a98MW2gs And make sure you give perms wild.wildtp and wild.wildtp.world.*

**Comment by xxyaboimazinxx** [comment]
Could u please try fix my factions config, I want it to only load on factions world
Too

**Comment by Qballl** [comment]
I dont know factions much

**Comment by xxyaboimazinxx** [comment]
All I need is to just have it in one world, is that possible with factions, please help I’m stuck with this shitt

**Comment by Qballl** [comment]
I really dont know been too long since I used factions. Unless you mean this plugin in which case you cant load it for one world
