### ISSUE TITLE
Issue with teleporting

### ISSUE THREAD

**Issue by idnthvn** [Qballl/WildernessTp#7]
Using Thermos 1.7.10-1614 Build 57   (build 58 breaks EnderIO)
Wilderness TP 3.3.0.1
using /wild  - Throws me 256 Blocks into the Air. landing on whatever is there. 
      ----Great for overworlds.
Nether issue, Still throws me 256 Blocks in the air, lands on top layer of 128
Cant mine Bedrock....... so it does me no good. 
I like this plugin alot and finally have one that doesnt spawn players in the ground. However i hope this can be address for the nether.
So far great plugin, but having to use RandomPort untill this is fixed

**Comment by Qballl** [comment]
What other plugins/mods are you using and send me your config using hastebin or pastebin please

**Comment by Qballl** [comment]
@idnthvn Please provide more info such as any and all other plugins/mods. Your log when you do the command. And send you config. For the log and config please use hastebin or Pastebin like I said before.

**Comment by idnthvn** [comment]
Sorry @Qballl , just got on and seen this.
This is my Config File:  http://pastebin.com/U0yU0qMG
Following Mods:
TreeCapitator-universal-2.0.4
advanced-machines-59.0.2
AdvancedSolarPanel-1.73.10-3.5.1
ae2stuff-rv3-0.5.1.9-mc1.7.10
AFSU-1.2.3a-Freeza
appliedenergistics2-rv3-alpha-0 (i changed some code so you wont find this online)
AsieLib-1.7.10-0.4.5
AsyncWorldEditInjector
bdlib-1.9.4.109-mc1.7.10
BigReactors-0.4.3A
BiomesOPlenty-1.7.10-2.1.0.2027-universal
buildcraft-7.1.17
buildcraft-compat-7.1.5
Carpenter's Blocks v3.3.8-MC1.7.10
Chisel-2.9.5.11
CodeChickenCore1.7.10-1.0.7.47
COFHCore3.1.3-328
Compactmachines1.21
Compact Solars-4.4.41.316
Computronics-1.6.0
CraftingPillars-1.6.1
DiscordIntergration-2.0.1
DragonAPI 1.7.10V
EnderCore-0.2.0.36
EnderIO-2.3.0.428
EnderStorage-1.4.7.38
EnderZoo-1.0.15.32
Eureka-3.0.2
ExtraCells-2.3.14b197
extrautilities-1.2.12
GregsLighting-1.11.2
IC2Nuclear Control-2.4.1a
IGW-MOD-1.1.12-34
immersiveEngineering-0.7.7
immibis-core-59.1.4
immibis-microblocks-59.1.2
industrialcraft-2-2.2.823
inventorytweaks-1.59-152
ironchest-6.0.62.742
keyandcodelock-1.4
mantle-0.3.2b
mcjtylib-1.8.1
Mekanism9.1.0.281
MekanismGenerators9.1.0.281
MekanismTools9.1.0.281
MineFactoryReloaded2.8.2B1-199
MineTweaker3-3.0.10B
Minetweakerrecipemaker*1.1.0.11
mobiousCore-1.2.5-Thermos
ModTweaker2-0.9.6
ModularPowersuits-0.11.0.300
neiaddons-1.12.12.40
NetherOres-2.3.2B1-23
NotEnoughItems-1.0.5.120
numina-0.4.0.131
OpenBlocks-1.5.1
OpenComputers-1.6.0.7
OpenModslib-0.9.1
OpenModularTurrets-2.2.4-225
Opis-1.2.5
Pams HarvestCraft-1.7.10Lb
PneumaticCraft-1.12.7-150
PowerConverters-3.3.0
ProjectRed-4.7.0pre12.95 (all of them)
RailCraft-9.12.2
ReactorCraft1.7.10V15
RotaryCraft1.7.10V15
StevesCarts-2.0.0.b18
TConstruct-1.8.8
ThermalDynamics-1.2.0-171
ThermalExpansion-4.1.4-247
ThermalFoundation-1.2.5-1153
UniDict-2.8d
Waila-1.5.10
WorldEdit-Forge-6.1.1
WR-CBE-1.4.1.11

Plugins:
AntiExplosions
AntiShare
AreaShop
ASyncWorldEdit
AutoMessage
Chestshop
citizens-2.0.13-Cauldron
CoreProtect
EnjinPlugin
Essentials
EssentialsAntiBuild
EssentialsChat
EssentiaslSpawn
Forge-Permittor
ItemRestrict
ModifyWorld
Multiverse Core
Multiverse Portals
OpenInventory
PermissionsEx
PhatLoots
randomport (using this along side with your plugin so i have some sort of rtp)
Towny
Vault
Votifier
WildTP
Worldedit
WorldGuard

When i use your plugin, everything works, no errors. Just throws me 256 blocks in the air, and then in the nether still throws me 256 but of course land on the bedrock at level 128

**Comment by Qballl** [comment]
Can you send me the ip and do I have to join with forge? If so dont bother the ip I would like to test on your server thats why I ask

**Comment by idnthvn** [comment]
its under technicpack.net its called LiteBox
http://www.technicpack.net/modpack/litebox.741396

**Comment by Qballl** [comment]
ok Ill try joining may take me a while my computer is well crap its like 8 or plus years old so you know not up to todays standards :(

**Comment by idnthvn** [comment]
@Qballl  It will take about 2.5 Gigs of ram to run

**Comment by Qballl** [comment]
Aw shit I only got 2 lets try this

**Comment by Qballl** [comment]
Just send the ip and Ill join when I get a chance to test it.

**Comment by idnthvn** [comment]
@Qball. It's in the modpack preset
But it's litebox.mcserver.ws

**Comment by Qballl** [comment]
The offical litebox server?

**Comment by idnthvn** [comment]
yes

**Comment by Qballl** [comment]
Nice

**Comment by Qballl** [comment]
Ok I have been able to get on your server and the problem with the nether is that the biome is not Hell so my plugin cant tell that the highest block is 128 I may make a quick update just for you that will allow you to say that the world is nether or not. But for why it throws to 256 constantly I dont know why

**Comment by Qballl** [comment]
Here is an updated version that "should" fix the nether issue for you I am unable to test due to not haveing a Thermos server and dont have time to set one up.
[WildTp.jar.zip](https://github.com/Qballl/WildernessTp/files/487637/WildTp.jar.zip)
Had to zip it so just unzip

**Comment by idnthvn** [comment]
awesome, ill test it out and let you know

**Comment by Qballl** [comment]
G8 m8

**Comment by Qballl** [comment]
Im gonna close it for now as I got on and nether was working. I wont turn off comments so if you need help still just look in the close section. If you find a new issue then open a new issue.
