### ISSUE TITLE
If you do /wild twice you tp to the same location 

### ISSUE THREAD

**Issue by GabyTRH** [Qballl/WildernessTp#70]
Hi, I have a 1.15 survival server, its just one world no network no thing, when I added the wild plugin and tried to use it, it said "Cannot use command in this world" so I opened the gui and added my world through chat. Even thought the teleport worked once if you do it again it teleports you back to the same place. Please help, thanks. 
[WildConfig.txt](https://github.com/Qballl/WildernessTp/files/3992315/WildConfig.txt)

**Comment by Qballl** [comment]
Look at the bottom of your config at worlds and you should see the issue. If not let me know (Hint compare world to survival you should see the problem)

**Comment by GabyTRH** [comment]
Thanks it got fixed
