### ISSUE TITLE
/wild [Biome] just does a random teleport?

### ISSUE THREAD

**Issue by Weasel-Beans** [Qballl/WildernessTp#72]
A player mentioned that they can't use /wild [biome] to go to a specific biome. They have the permission 'wild.wildtp.biome.*', and I'm not aware of anything that would stop this. The same happens to me when I try it as an OP, it just does the regular random teleport.

**Comment by Qballl** [comment]
It's very buggy and is removed from the rewrite as it doesn't work right

**Comment by Weasel-Beans** [comment]
Yeah, I tried enabling this a couple days ago to discover today that it completely breaks the server when the command is typed
