### ISSUE TITLE
Compatibility with WorldBorder? Limitations of square/rectangle settings.

### ISSUE THREAD

**Issue by Weasel-Beans** [Qballl/WildernessTp#74]
Is it possible to have this plugin made compatible with WorldBorder? With say options like being able to /wild anywhere within the designated border. Or if that's not possible, to have the option of setting circular wild regions?

I would like people to be able to teleport to the outer parts of my map as those areas are 1.14+, but my border is circular, so players can sometimes be sent outside the border

**Comment by Qballl** [comment]
Unfortunately it's just not possible right now at least it may come latter but 3.x is more or less dead as I'm working on a complete rewrite and the border is still rectangular. For now I can only suggest lowering your range sorry
