### ISSUE TITLE
Lag caused by plugin

### ISSUE THREAD

**Issue by Castiella** [Qballl/WildernessTp#77]
https://timings.aikar.co/?id=79af25647fcc4177a34e497eb73d91f7

Any reason this could be caused?

TPS drops to 17 when anyone does /wild

**Comment by Castiella** [comment]
After investigation we have discovered that using /wild doesnt affect the TPS.

However, using /wild through an NPC via citizens does cause lag. 
We have repeated this with various other plugins, however it is just wild that lags when used via an NPC.

We use Command NPC for this function. It attaches a command to an npc and runs it in the form of /sudo

**Comment by Weasel-Beans** [comment]
https://timings.aikar.co/?id=ae0ab09ba8414fd980185f51b6252965

I also seem to have severe lag correlated with this plugin in the timings report. I have no idea what could cause it though, because using the command doesn't seem to cause much lag, and it usually doesn't do this.

**Comment by RonaldBunk** [comment]
Not much to do about, it's the chunk loading that takes its toll, especially if certain options are enabled/disabled like skipping certain biomes.
