### ISSUE TITLE
/wild [BUG]

### ISSUE THREAD

**Issue by ExceptedPrism3** [Qballl/WildernessTp#86]
**Describe the bug**
I'm on Spawn world and trying tp to world

**To Reproduce**
1. Change the config as mine: https://pastebin.com/wynFAA5z
2. Go to 'another world'
3. try to tp yourself into world
4. error pops up

**Screenshots**
https://pastebin.com/A6WMam30

**Comment by Qballl** [comment]
Did you figure out ypur issue?

**Comment by ExceptedPrism3** [comment]
> Did you figure out ypur issue?

Yes
