### ISSUE TITLE
[Feature Request] Message-on-teleport: []

### ISSUE THREAD

**Issue by Castiella** [Qballl/WildernessTp#89]
Please forgive me if this is already possible but I'd like a way to customize the message sent when players are randomly teleported. 

Message-on-teleport: []

Example of this  configurated:
Message-on-teleport: &bYou have been teleported in our SMP world! Don't forget to /sethome if you like the spot!

Thank you! :)

**Comment by Qballl** [comment]
You can already for the most part do that with the lang file using teleporting. That sends just a bit before teleport happens like milliseconds before
