### ISSUE TITLE
[Feature Request] Add world name as argument to wild/rtp command

### ISSUE THREAD

**Issue by viveleroi** [Qballl/WildernessTp#94]
**Is your feature request related to a problem? Please describe.**
Please add a command that accepts a world as an argument. Our spawn world is not our main world, and often players want to teleport to our resource world but this is all a two-step process right now:

1. Teleport to intended world
2. rtp

I'd much prefer this be a one-step process.

**Describe the solution you'd like**
For example, `/wild [world]`. 

**Describe alternatives you've considered**
Other plugins, but this one works well for us especially with paper async support.

**Additional context**
N/A

**Comment by Qballl** [comment]
Shouldn't be too hard to add will try to have something out before too long

**Comment by viveleroi** [comment]
Would *greatly* appreciate it. This would make a big improvement for us.

**Comment by Qballl** [comment]
Posting an update for it now thanks to @Azoraqua for the main implementation had a small bug fixed now
