### ISSUE TITLE
[BUG] Wilderness portal doesn't teleport unless the player moves whilst inside it

### ISSUE THREAD

**Issue by aco4** [Qballl/WildernessTp#99]
**Describe the bug**
Simply entering the wilderness portal does not teleport the player; they have to move to another block whilst inside it for it to work.

**To Reproduce**
1. Create a wildtp portal that is vertical in shape (nether portal style, not end portal style)
2. Walk into it
3. No tp occurs
4. Walk to another block, then you tp.

**Expected behavior**
You should teleport as soon as you enter the wildtp block.

**Screenshots**
none

**Additional context**
none

**Comment by Qballl** [comment]
Odd that I never noticed that must have to do with the fact I make the test ones in open space and walk thru it but if there was a wall behind that wouldn't work

**Comment by Qballl** [comment]
Fixed now will push soon
